### ISSUE TITLE
Can't create proxys in Windows

### ISSUE THREAD

**Issue by matAlmeida** [matAlmeida/mtg-proxy#2]
**Describe the bug**
I installed the CLI in windows WSL and CMD, and in neither of then i was able to create the proxys

**To Reproduce**
1. Install `mtg-proxy` globaly on WSL or CMD with `npm i -g mtg-proxy`
2. Create a `pauper-landfall.txt` usign NotePad with the following list:
```
2 Kird Ape
4 Makindi Sliderunner
2 Snapping Gnarlid
4 Crop Rotation
4 Swell of Growth
1 Gruul Turf
1 Selesnya Sanctuary
1 Teetering Peaks
```
3. Go to the folder where the `pauper-landfall.txt` is located and run `mtg-proxy create --from="pauper-landfall.txt"`

**Expected behavior**
The PDF created in the folder

**Output**
```
/home/matalmeida/.nvm/versions/node/v10.16.0/lib/node_modules/mtg-proxy/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Argument "path" passed to exists(path) must be a string. Received undefined
    at Object.validateArgument [as argument] (/home/matalmeida/.nvm/versions/node/v10.16.0/lib/node_modules/mtg-proxy/node_modules/fs-jetpack/lib/utils/validate.js:109:11)
    at Object.validateInput (/home/matalmeida/.nvm/versions/node/v10.16.0/lib/node_modules/mtg-proxy/node_modules/fs-jetpack/lib/exists.js:8:12)
    at Object.exists (/home/matalmeida/.nvm/versions/node/v10.16.0/lib/node_modules/mtg-proxy/node_modules/fs-jetpack/lib/jetpack.js:107:14)
    at Command.run (/home/matalmeida/.nvm/versions/node/v10.16.0/lib/node_modules/mtg-proxy/src/commands/create.js:31:21)
    at Runtime.<anonymous> (/home/matalmeida/.nvm/versions/node/v10.16.0/lib/node_modules/mtg-proxy/node_modules/gluegun/build/runtime/run.js:101:58)
    at step (/home/matalmeida/.nvm/versions/node/v10.16.0/lib/node_modules/mtg-proxy/node_modules/gluegun/build/runtime/run.js:43:23)
    at Object.next (/home/matalmeida/.nvm/versions/node/v10.16.0/lib/node_modules/mtg-proxy/node_modules/gluegun/build/runtime/run.js:24:53)
    at /home/matalmeida/.nvm/versions/node/v10.16.0/lib/node_modules/mtg-proxy/node_modules/gluegun/build/runtime/run.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/home/matalmeida/.nvm/versions/node/v10.16.0/lib/node_modules/mtg-proxy/node_modules/gluegun/build/runtime/run.js:14:12)
```

**Comment by matAlmeida** [comment]
Problem as cause due to some gluegun/my code bug.

Removed all gluegun code to let it more clean and have more control over the source code.

Fixed in 2d1b1dbaa085a653349bf792adab959c1834bb00
